spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: media-service
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3307/media
    username: pengli
    password: password
    
server:
  servlet:
    context-path: /api
  port: 7000
  
logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE