DROP TABLE PHOTOS;
CREATE TABLE PHOTOS (
  ID MEDIUMINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50)  NOT NULL,
  THUMBNAIL VARCHAR(50),
  DATE VARCHAR(8),
  PLACE VARCHAR(96),
  PERSON VARCHAR(96),
  DESCRIBTION VARCHAR(1024),
  PRIMARY KEY (ID)
);

DROP TABLE PERSONS;
CREATE TABLE PERSONS (
  ID MEDIUMINT,
  PERSON VARCHAR(96)
);

